# Generated by Django 4.2.3 on 2023-07-14 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_file', models.FileField(upload_to='files')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
